feat(test): jest 28 support
add suport for jest 28 in stencil.

this commit is the first pass at support a new version of jest in
stencil in well over a year, and the first to use the new package-based
architecture.

this commit was generated using the steps that are outline in the README
file of the jest directory, [available here](https://github.com/ionic-team/stencil/blob/d725ac9ef73f9700feb773d4a65e3ea988db6d31/src/testing/jest/README.md?plain=1).

note: some commits of the original pr may be out of order with the
readme above. although the readme is permalinked, it did undergo some
changes between the time this pr's commits were created and the time this
pr was created. some items of note:
- the contents of `jest-27-and-under/` were copied into `jest-28/` using
  the latest available contents at the time - 6893954 (#4904).

in order to support jest 28, the following changes were made:
1. projects are now typed as `string` in v28:
   the typings for jest are causing the project to fail compilation. update
   the return value here, as `Config.Path` is now just a string
1. resolve TS4053 error in v28 facade:
   we had to resolve a typescript compilation error where we would run
   into typescript error TS4053. this was caused by this facade's
   implementation of `getJestPreset` returning a Jest preset that
   referenced Jest v28's `Config` interface. the TypeScript compiler did
   not know how to make sense of this import within the module, requiring
   us to manually import it
1. update typings of the preprocessor:
   in jest 28, preprocessors cannot return a string. rather, they must at
   minimum return `{ code : string }`. this commit resolves those
   compilation errors by using Jest's `TransformedSource` type and updating
   the return values of the function accordingly
1. migrate to jest-circus for v28:
   switch users over to jest-circus for v28, rather than jest-jasmine2.
   this makes it such that we are not required to force users to add
   jest-jasmine2 to their dependencies, since it was removed from jest in
   v28 (and published as a separate package).
1. handle updated environment export:
   the test environments export has changed in v28. update the require
   statement to handle this change.
1. remove jasmine globals:
   remove direct references to jasmine globals that were used in jest 28
   code. in some instnaces, puppeteer code that is not versioned (per
   version of jest) had to be modified to ensure that we did not attempt to
   reference a global `jasmine` that did not exist

finally, some backwards compatability code was removed from the new
`jest-28/` directory. it did not need to be executed in this new
architecture (and can be siloed to `jest-27-and-under/`)

closes: 3348

STENCIL-955