refactor(test): resolve typing import issues
resolves an issue where adding typings from `@stencil/core/internal`
were causing failures of the build validation step in CI (`npm run
test.dist`). this had caused argument types for a handful of functions
to be typed as `any` as opposed to known types provided by stencil.

previous to this change, naively adding types to use stencil
declarations in `./src/testing/jest/jest-facade.ts` would cause the
following error when running the build validation step against a build
of stencil:
```
> node scripts/build --validate-build

🐡  Validated packages
Error: 🧨  testing/jest/jest-stencil-connector.d.ts(29,55): error TS2307: Cannot find module '../../declarations' or its corresponding type declarations.
testing/jest/jest-stencil-connector.d.ts(29,109): error TS2307: Cannot find module '../../declarations' or its corresponding type declarations.
```

with this change, we can safely type `jest-facade.ts` and have a uniform
type used throughout the directory/jest supporting submodules.

STENCIL-961: Fix type resolutions from declarations