chore(wdio): fix build issues
fix a build issue where running `npm run build` twice in the `test/wdio`
directory would result in the following failure:
```
 [47:48.5]  aborted build, 343ms  MEM: 359.2MB

[ ERROR ]  TypeScript: event-custom-type/cmp.tsx:3:44
           Cannot find module '../components' or its corresponding type declarations.

      L3:  import { EventCustomTypeCustomEvent } from '../components';

[47:48.5]  build failed in 343 ms
```

This was introduced in https://github.com/ionic-team/stencil/pull/5493,
where the import statement was not correctly ported over. As a result,
type resolution would fail under `tsconfig.json#moduleResoution` having
a value of 'Node16'